---
# This playbook deploys the whole application stack in this site.
#
# Example:
# ansible-playbook -i inventory/proxmo site.yml

- hosts: running

  vars_prompt:
    - name: CONFIRM
      prompt: Just to confirm you will install stuff
      default: "no"
      private: no
  pre_tasks:
    - fail:
        msg: "No deployment this time."
      when: CONFIRM|lower != 'yes'

  roles:
    - ubuntu-repositories
    - debian-software-essentials
    - debian-software-ntp

#  tasks:
#    - name: get hostname
#      command: /bin/hostname
#      changed_when: False
#      register: hostname
#    - name: get uptime
#      shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
#      changed_when: False
#      register: uptime
#    - debug: var={{ item }}
#      with_items:
#        - hostname.stdout
#        - uptime.stdout
