---

- name: "NTP"
  block:
    - name: "Ensure package ntp is installed"
      package:
        name: ntp
        state: latest
    - name: "Build and write /etc/ntp.conf file"
      template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart ntpd
  tags:
    - debian-software-ntp
